/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-container': '#49494a',
        error: '#ffb4ab',
        'secondary-fixed-dim': '#c8c6c7',
        'primary-fixed': '#ffdad5',
        'inverse-surface': '#e5e2e1',
        'surface-container-low': '#1c1b1b',
        surface: '#131313',
        'surface-tint': '#ffb4a9',
        'on-secondary-container': '#bab8b9',
        'on-error-container': '#ffdad6',
        background: '#131313',
        outline: '#ac8883',
        'inverse-primary': '#bc140f',
        'on-surface-variant': '#e5bdb7',
        'surface-variant': '#353534',
        'on-primary-container': '#5c0001',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#1b1b1c',
        'on-error': '#690005',
        'on-surface': '#e5e2e1',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'inverse-on-surface': '#313030',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#005236',
        'on-primary-fixed': '#410000',
        secondary: '#c8c6c7',
        'primary-container': '#ff5543',
        'secondary-fixed': '#e5e2e3',
        'primary-fixed-dim': '#ffb4a9',
        'tertiary-fixed': '#6ffbbe',
        'on-background': '#e5e2e1',
        'on-tertiary-container': '#00311f',
        'surface-container-high': '#2a2a2a',
        'surface-container': '#201f1f',
        'on-secondary': '#303031',
        'on-primary': '#690001',
        'tertiary-container': '#00a572',
        'on-tertiary': '#003824',
        'on-secondary-fixed-variant': '#474647',
        'surface-container-highest': '#353534',
        'on-primary-fixed-variant': '#930003',
        'outline-variant': '#5c403c',
        tertiary: '#4edea3',
        primary: '#ffb4a9',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-fixed': '#002113',
      },
      fontFamily: {
        'orion-headline': ['Montserrat', 'sans-serif'],
        'orion-body': ['Montserrat', 'sans-serif'],
        'orion-label': ['Montserrat', 'sans-serif'],
        'playwrite': ['"Playwrite IE"', 'cursive'],
      },
      borderRadius: {
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
};
